[package]
name = "kotowari-cli"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "kotowari"
path = "src/main.rs"

[dependencies]
kotowari = { path = "crates/kotowari", version = "0.3.0" }
serde_json = "1"

[dev-dependencies]
kotowari-core = { path = "crates/kotowari-core", version = "0.3.0" }
assert_cmd = "2"
proptest = "1"
tempfile = "3"
serde-saphyr = "1"

[workspace]
members = ["crates/kotowari", "crates/kotowari-core", "crates/kotowari-source-analysis", "crates/kotowari-markdown-schema", "crates/kotowari-markdown-schema-io", "crates/kotowari-mds"]
exclude = ["experiments"]
resolver = "3"
