[package]
name = "kotowari"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kotowari"
path = "src/main.rs"

[dependencies]
kotowari-core = { path = "crates/kotowari-core" }

[dev-dependencies]
assert_cmd = "2"
proptest = "1"
tempfile = "3"
serde_json = "1"
serde-saphyr = "1"

[workspace]
members = ["crates/kotowari-core"]
exclude = ["experiments"]
resolver = "3"
