[package]
name = "kotowari-core"
version = "0.3.0"
edition = "2024"

[lib]
name = "kotowari_core"
path = "src/lib.rs"

[dependencies]
kotowari-markdown-schema = { path = "../kotowari-markdown-schema", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde-saphyr = "1"
globset = "0.4"
serde_json = "1"
regex = "1"
sha2 = "0.10"
markdown = "1"
